name: Validate JSON
on: [push, pull_request]
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate locale.json
        uses: MrGriefs/validate-json-action@master
        with:
          schema: ./locale.schema.json
          jsons: ./??/locale.json
      - name: Validate JSON config
        uses: MrGriefs/validate-json-action@master
        with:
          schema: ./schema.json
          jsons: ./??/!(locale).json